export enum NotifyEnums {
	SUCCESS = 'success',
	ERROR = 'error',
	WARNING = 'warning',
	INFO = 'info',
}

export enum StatusCodeEnums {
	UNAUTHORIZED = 401,
	FORBIDDEN = 403,
	NOT_FOUND = 404,
}

export enum ACTION_ENUM {
	EDIT = 'EDIT',
	DELETE = 'DELETE',
	ADD = 'ADD',
	NAVIGATE = 'NAVIGATE',
	MORE = 'MORE',
	CUSTOM = 'CUSTOM',
}

export enum TYPE_COMPONENT {
	LINK = 'LINK',
	CHECKBOX = 'CHECKBOX',
	BLOCK_CHECKBOX = 'BLOCK-CHECKBOX',
	ACTIONS = 'ACTIONS',
	TAG = 'TAG',
	DATE = 'DATE',
	CURRENCY = 'CURRENCY',
	NUMBER = 'NUMBER',
	INPUT = 'INPUT',
	TEXT_AREA = 'TEXT-AREA',
	INPUT_NUMBER = 'INPUT-NUMBER',
	SELECT = 'SELECT',
	DATE_PICKER = 'DATE-PICKER',
	INPUT_PASSWORD = 'INPUT-PASSWORD',
	TAG_LIST = 'TAG-LIST',
	NUMBER_ORDER = 'NUMBER-ORDER',
	RADIO_GROUP = 'RADIO-GROUP',
	CUSTOM = 'CUSTOM',
	NUMBER_PICKER = 'NUMBER-PICKER',
}

export enum STATUS {
	ACTIVE = 'ACTIVE',
	INACTIVE = 'INACTIVE',
}
